services:
  # Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: backend_proxy
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - tasks
      - authentication
    restart: unless-stopped

  # Tasks
  tasks:
    build:
      context: ./Tasks
      dockerfile: Dockerfile
    container_name: tasks_app
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - SQLALCHEMY_ECHO=${SQLALCHEMY_ECHO}
      - ENV=${ENV}
    expose:
      - "8001"
    restart: unless-stopped

  # Authentication
  authentication:
    build:
      context: ./Authentication
      dockerfile: Dockerfile
    container_name: authentication_app
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - SQLALCHEMY_ECHO=${SQLALCHEMY_ECHO}
      - ENV=${ENV}
      - FRONTEND_ORIGIN=${FRONTEND_ORIGIN}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - SECRET_KEY=${SECRET_KEY}
    expose:
      - "8002"
    restart: unless-stopped
