services:
  # Tasks
  tasks:
    build:
      context: ./Tasks
      dockerfile: Dockerfile
    container_name: tasks_app
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - SQLALCHEMY_ECHO=${SQLALCHEMY_ECHO}
      - ENV=${ENV}
    ports:
      - "8080:8080"
    restart: unless-stopped
