'use client';

import React, { useState, useEffect, useMemo } from 'react';
import {
  Card,
  CardContent,
  CardActions,
  Container,
  Typography,
  Button,
  Chip,
  Paper,
  Alert,
  Stack,
} from '@mui/material';
import {
  TrendingUp,
  People,
  CheckCircle,
  PictureAsPdf,
  TableChart,
  Timer,
} from '@mui/icons-material';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { taskMockData } from '@/mocks/staff/taskMockData';

interface ReportType {
  id: string;
  title: string;
  description: string;
  icon: React.ReactNode;
  category: string;
  estimatedTime: string;
  dataPoints: number;
}

export default function ReportGeneration() {
  const [selectedReport, setSelectedReport] = useState<string | null>(null);
  const [exportType, setExportType] = useState<'pdf' | 'excel' | null>(null);
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  const currentDate = useMemo(() => new Date().toLocaleDateString(), []);

  // Calculate data points from mock data
  const totalTasks = taskMockData.tasks.length;
  const completedTasks = taskMockData.tasks.filter(
    (task) => task.status === 'Completed'
  ).length;
  const inProgressTasks = taskMockData.tasks.filter(
    (task) => task.status === 'In Progress'
  ).length;
  const blockedTasks = taskMockData.tasks.filter(
    (task) => task.status === 'Blocked'
  ).length;
  const uniqueProjects = new Set(
    taskMockData.tasks.map((task) => task.projectName)
  ).size;
  const uniqueDepartments = new Set(
    taskMockData.tasks.flatMap((task) =>
      task.assignedUsers.map((user) => user.department)
    )
  ).size;

  // PDF Export Functions
  const generateTaskCompletionPDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    let yPos = 20;

    // Header
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text('Task Completion/Status Report', pageWidth / 2, yPos, { align: 'center' });

    yPos += 10;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated: ${currentDate}`, pageWidth / 2, yPos, { align: 'center' });
    doc.text(`Generated by: ${taskMockData.currentUser.name} (${taskMockData.currentUser.role})`, pageWidth / 2, yPos + 5, { align: 'center' });

    yPos += 20;

    // Summary Statistics
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Summary Statistics', 14, yPos);
    yPos += 10;

    const stats = [
      ['Total Tasks', totalTasks.toString()],
      ['Completed Tasks', `${completedTasks} (${((completedTasks / totalTasks) * 100).toFixed(1)}%)`],
      ['In Progress Tasks', `${inProgressTasks} (${((inProgressTasks / totalTasks) * 100).toFixed(1)}%)`],
      ['Blocked Tasks', `${blockedTasks} (${((blockedTasks / totalTasks) * 100).toFixed(1)}%)`],
      ['Active Projects', uniqueProjects.toString()],
      ['Departments', uniqueDepartments.toString()],
    ];

    autoTable(doc, {
      startY: yPos,
      head: [['Metric', 'Value']],
      body: stats,
      theme: 'grid',
      headStyles: { fillColor: [102, 126, 234], fontSize: 11 },
      styles: { fontSize: 10 },
      margin: { left: 14, right: 14 },
    });

    yPos = (doc as any).lastAutoTable.finalY + 15;

    // Task Details by Status
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Task Details', 14, yPos);
    yPos += 10;

    const taskData = taskMockData.tasks.map((task) => [
      task.title.length > 30 ? task.title.substring(0, 30) + '...' : task.title,
      task.status,
      task.priority,
      task.projectName.length > 20 ? task.projectName.substring(0, 20) + '...' : task.projectName,
      task.assignedUsers.length > 0 ? task.assignedUsers[0].name : 'Unassigned',
      task.completedDate || 'N/A',
    ]);

    autoTable(doc, {
      startY: yPos,
      head: [['Task Title', 'Status', 'Priority', 'Project', 'Assignee', 'Completed']],
      body: taskData,
      theme: 'striped',
      headStyles: { fillColor: [102, 126, 234], fontSize: 9 },
      styles: { fontSize: 8, cellPadding: 3 },
      columnStyles: {
        0: { cellWidth: 50 },
        1: { cellWidth: 25 },
        2: { cellWidth: 20 },
        3: { cellWidth: 35 },
        4: { cellWidth: 30 },
        5: { cellWidth: 25 },
      },
      margin: { left: 14, right: 14 },
    });

    // Save PDF
    doc.save(`Task-Completion-Report-${Date.now()}.pdf`);
  };

  const generateProjectPerformancePDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    let yPos = 20;

    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text('Project Performance Analytics', pageWidth / 2, yPos, { align: 'center' });

    yPos += 10;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated: ${currentDate}`, pageWidth / 2, yPos, { align: 'center' });

    yPos += 20;

    // Group tasks by project
    const projectMap = new Map<string, any[]>();
    taskMockData.tasks.forEach((task) => {
      if (!projectMap.has(task.projectName)) {
        projectMap.set(task.projectName, []);
      }
      projectMap.get(task.projectName)!.push(task);
    });

    const projectData = Array.from(projectMap.entries()).map(([projectName, tasks]) => {
      const completed = tasks.filter((t) => t.status === 'Completed').length;
      const inProgress = tasks.filter((t) => t.status === 'In Progress').length;
      const blocked = tasks.filter((t) => t.status === 'Blocked').length;
      const completionRate = ((completed / tasks.length) * 100).toFixed(1);

      return [
        projectName,
        tasks.length.toString(),
        completed.toString(),
        inProgress.toString(),
        blocked.toString(),
        `${completionRate}%`,
      ];
    });

    autoTable(doc, {
      startY: yPos,
      head: [['Project Name', 'Total Tasks', 'Completed', 'In Progress', 'Blocked', 'Completion Rate']],
      body: projectData,
      theme: 'grid',
      headStyles: { fillColor: [76, 175, 80], fontSize: 10 },
      styles: { fontSize: 9, halign: 'center' },
      margin: { left: 14, right: 14 },
    });

    doc.save(`Project-Performance-Report-${Date.now()}.pdf`);
  };

  const generateTeamProductivityPDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    let yPos = 20;

    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text('Team Productivity Report', pageWidth / 2, yPos, { align: 'center' });

    yPos += 10;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated: ${currentDate}`, pageWidth / 2, yPos, { align: 'center' });

    yPos += 20;

    // Group tasks by user
    const userTaskMap = new Map<string, any[]>();
    taskMockData.tasks.forEach((task) => {
      task.assignedUsers.forEach((user) => {
        if (!userTaskMap.has(user.name)) {
          userTaskMap.set(user.name, []);
        }
        userTaskMap.get(user.name)!.push(task);
      });
    });

    const userData = Array.from(userTaskMap.entries()).map(([userName, tasks]) => {
      const completed = tasks.filter((t) => t.status === 'Completed').length;
      const inProgress = tasks.filter((t) => t.status === 'In Progress').length;
      const userInfo = taskMockData.tasks
        .flatMap((t) => t.assignedUsers)
        .find((u) => u.name === userName);

      return [
        userName,
        userInfo?.department || 'N/A',
        userInfo?.role || 'N/A',
        tasks.length.toString(),
        completed.toString(),
        inProgress.toString(),
        ((completed / tasks.length) * 100).toFixed(1) + '%',
      ];
    });

    autoTable(doc, {
      startY: yPos,
      head: [['Team Member', 'Department', 'Role', 'Total Tasks', 'Completed', 'In Progress', 'Completion Rate']],
      body: userData,
      theme: 'striped',
      headStyles: { fillColor: [33, 150, 243], fontSize: 9 },
      styles: { fontSize: 8 },
      margin: { left: 14, right: 14 },
    });

    doc.save(`Team-Productivity-Report-${Date.now()}.pdf`);
  };

  const reportTypes: ReportType[] = [
    {
      id: 'task-completion-status',
      title: 'Task Completion/Status Report',
      description:
        'Comprehensive overview of task completion rates, status distribution, and progress tracking across all projects. Includes breakdown by priority, department, and timeline analysis.',
      icon: <CheckCircle sx={{ fontSize: 40, color: 'primary.main' }} />,
      category: 'Task Management',
      estimatedTime: '2-3 minutes',
      dataPoints: totalTasks,
    },
    {
      id: 'project-performance',
      title: 'Project Performance Analytics',
      description:
        'Detailed analysis of project performance metrics including task distribution, completion rates, team efficiency, and milestone tracking. Provides insights into project health and bottlenecks.',
      icon: <TrendingUp sx={{ fontSize: 40, color: 'success.main' }} />,
      category: 'Project Analytics',
      estimatedTime: '3-4 minutes',
      dataPoints: uniqueProjects,
    },
    {
      id: 'team-productivity',
      title: 'Team Productivity Report',
      description:
        'In-depth productivity analysis covering individual and team performance, workload distribution, task assignment patterns, and collaboration metrics across departments.',
      icon: <People sx={{ fontSize: 40, color: 'info.main' }} />,
      category: 'Team Analytics',
      estimatedTime: '2-3 minutes',
      dataPoints: taskMockData.tasks.flatMap((task) => task.assignedUsers).length,
    },
  ];

  const handleExportReport = async (reportId: string, type: 'pdf' | 'excel') => {
    setSelectedReport(reportId);
    setExportType(type);

    await new Promise((resolve) => setTimeout(resolve, 500));

    if (type === 'pdf') {
      switch (reportId) {
        case 'task-completion-status':
          generateTaskCompletionPDF();
          break;
        case 'project-performance':
          generateProjectPerformancePDF();
          break;
        case 'team-productivity':
          generateTeamProductivityPDF();
          break;
      }
    } else {
      console.log('Excel export for:', reportId);
      alert('Excel export will be implemented next!');
    }

    setSelectedReport(null);
    setExportType(null);
  };

  const getCategoryColor = (category: string) => {
    const colors: { [key: string]: string } = {
      'Task Management': 'primary',
      'Project Analytics': 'success',
      'Team Analytics': 'info',
    };
    return colors[category] || 'default';
  };

  if (!mounted) {
    return null;
  }

  return (
    <div style={{ backgroundColor: '#ffffff', minHeight: '100vh' }} suppressHydrationWarning>
      <Container maxWidth="lg" sx={{ py: { xs: 2, sm: 3, md: 4 } }}>
        {/* Header Section */}
        <Paper
          elevation={0}
          sx={{
            p: { xs: 2, sm: 3, md: 4 },
            mb: { xs: 2, sm: 3, md: 4 },
            background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
            color: 'white',
            borderRadius: 2,
          }}
        >
          <Typography
            variant="h3"
            component="h1"
            gutterBottom
            fontWeight={600}
            sx={{
              fontSize: { xs: '1.75rem', sm: '2.5rem', md: '3rem' },
            }}
          >
            Reports Dashboard
          </Typography>
          <Typography
            variant="h6"
            sx={{
              opacity: 0.9,
              mb: { xs: 1, sm: 2 },
              fontSize: { xs: '1rem', sm: '1.15rem', md: '1.25rem' },
            }}
          >
            Welcome, {taskMockData.currentUser.name} ({taskMockData.currentUser.role})
          </Typography>
          <Typography
            variant="body1"
            sx={{
              opacity: 0.85,
              fontSize: { xs: '0.875rem', sm: '1rem' },
            }}
          >
            Generate comprehensive reports and analytics to gain insights into task management,
            team performance, and organizational productivity.
          </Typography>
        </Paper>

        {selectedReport && exportType && (
          <Alert severity="success" sx={{ mb: { xs: 2, sm: 3 } }}>
            Exporting to {exportType === 'pdf' ? 'PDF' : 'Excel'}... This may take a few moments.
          </Alert>
        )}

        {/* Reports Section */}
        <Typography
          variant="h5"
          fontWeight={600}
          sx={{
            mb: { xs: 2, sm: 3 },
            fontSize: { xs: '1.25rem', sm: '1.5rem' },
          }}
        >
          Available Reports
        </Typography>

        {/* Single Column Layout */}
        <Stack spacing={{ xs: 2, sm: 2.5, md: 3 }}>
          {reportTypes.map((report) => (
            <Card
              key={report.id}
              elevation={2}
              sx={{
                transition: 'transform 0.2s, box-shadow 0.2s',
                '&:hover': {
                  transform: 'translateY(-2px)',
                  boxShadow: 4,
                },
              }}
            >
              <CardContent sx={{ p: { xs: 2, sm: 2.5, md: 3 } }}>
                <Stack
                  direction={{ xs: 'column', sm: 'row' }}
                  alignItems={{ xs: 'flex-start', sm: 'center' }}
                  spacing={{ xs: 1.5, sm: 2 }}
                  sx={{ mb: 2 }}
                >
                  <Paper
                    elevation={0}
                    sx={{
                      p: { xs: 1, sm: 1.5 },
                      borderRadius: 2,
                      bgcolor: 'action.hover',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                    }}
                  >
                    {report.icon}
                  </Paper>

                  <Stack sx={{ flexGrow: 1, width: '100%' }} spacing={1}>
                    <Stack
                      direction={{ xs: 'column', sm: 'row' }}
                      alignItems={{ xs: 'flex-start', sm: 'center' }}
                      justifyContent="space-between"
                      spacing={1}
                    >
                      <Typography
                        variant="h6"
                        fontWeight={600}
                        sx={{ fontSize: { xs: '1rem', sm: '1.15rem', md: '1.25rem' } }}
                      >
                        {report.title}
                      </Typography>
                      <Chip
                        label={report.category}
                        size="small"
                        color={getCategoryColor(report.category) as any}
                        sx={{ fontSize: { xs: '0.7rem', sm: '0.75rem' } }}
                      />
                    </Stack>

                    <Typography
                      variant="body2"
                      color="textSecondary"
                      sx={{
                        fontSize: { xs: '0.813rem', sm: '0.875rem' },
                        lineHeight: 1.6,
                      }}
                    >
                      {report.description}
                    </Typography>

                    <Stack
                      direction={{ xs: 'column', sm: 'row' }}
                      justifyContent="space-between"
                      alignItems={{ xs: 'flex-start', sm: 'center' }}
                      spacing={{ xs: 1, sm: 2 }}
                    >
                      <Stack direction="row" alignItems="center" spacing={0.5}>
                        <Timer fontSize="small" sx={{ fontSize: { xs: 14, sm: 16 } }} />
                        <Typography
                          variant="caption"
                          color="textSecondary"
                          sx={{ fontSize: { xs: '0.75rem', sm: '0.813rem' } }}
                        >
                          {report.estimatedTime}
                        </Typography>
                      </Stack>
                      <Typography
                        variant="caption"
                        color="textSecondary"
                        sx={{ fontSize: { xs: '0.75rem', sm: '0.813rem' } }}
                      >
                        {report.dataPoints} data points
                      </Typography>
                    </Stack>
                  </Stack>
                </Stack>
              </CardContent>

              <CardActions sx={{ p: { xs: 2, sm: 2.5, md: 3 }, pt: 0 }}>
                <Stack
                  direction={{ xs: 'column', sm: 'row' }}
                  spacing={{ xs: 1, sm: 2 }}
                  sx={{ width: '100%' }}
                >
                  <Button
                    variant="contained"
                    fullWidth
                    startIcon={<PictureAsPdf />}
                    onClick={() => handleExportReport(report.id, 'pdf')}
                    disabled={selectedReport === report.id && exportType === 'pdf'}
                    sx={{
                      py: { xs: 1, sm: 1.25 },
                      fontSize: { xs: '0.875rem', sm: '0.938rem' },
                    }}
                  >
                    {selectedReport === report.id && exportType === 'pdf'
                      ? 'Exporting...'
                      : 'Export to PDF'}
                  </Button>
                  <Button
                    variant="outlined"
                    fullWidth
                    startIcon={<TableChart />}
                    onClick={() => handleExportReport(report.id, 'excel')}
                    disabled={selectedReport === report.id && exportType === 'excel'}
                    sx={{
                      py: { xs: 1, sm: 1.25 },
                      fontSize: { xs: '0.875rem', sm: '0.938rem' },
                    }}
                  >
                    {selectedReport === report.id && exportType === 'excel'
                      ? 'Exporting...'
                      : 'Export to Excel'}
                  </Button>
                </Stack>
              </CardActions>
            </Card>
          ))}
        </Stack>

        {/* Footer Info */}
        <Paper
          elevation={0}
          sx={{
            mt: { xs: 3, sm: 4 },
            p: { xs: 2, sm: 2.5, md: 3 },
            bgcolor: 'grey.50',
            borderRadius: 2,
            border: 1,
            borderColor: 'grey.200',
          }}
        >
          <Typography
            variant="body2"
            color="textSecondary"
            align="center"
            sx={{ fontSize: { xs: '0.75rem', sm: '0.875rem' } }}
          >
            Reports are generated based on current task data ({totalTasks} tasks, {uniqueProjects}{' '}
            projects, {uniqueDepartments} departments). All data is current as of {currentDate}.
          </Typography>
        </Paper>
      </Container>
    </div>
  );
}
